# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "主页"
  url = "#about"
  weight = 10

[[main]]
  name = "经历"
  url = "#experience"
  weight = 20

[[main]]
  name = "成就"
  url = "#accomplishments"
  weight = 30

[[main]]
  name = "文章"
  url = "#posts"
  weight = 40

[[main]]
  name = "项目"
  url = "#projects"
  weight = 50

[[main]]
  name = "演讲"
  url = "#talks"
  weight = 70

[[main]]
  name = "技能"
  url = "#skills"
  weight = 90

[[main]]
  name = "联系"
  url = "#contact"
  weight = 100

#[[main_right]]
#  name = "<i class='ai ai-coursera' style='font-size:1.5rem;line-height:1.25'></i>"
#  url = "https://www.coursera.org/user/94d1260a778d0a3918ef95b4c1063486"
#  weight = 10

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
[[main_right]]
  name = "<i class='ai ai-cv' style='font-size:1.5rem;line-height:1.25'></i>"
  url = "cv.pdf"
  weight = 40
